/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersListRouteImport } from './routes/usersList'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CsvreportRouteImport } from './routes/csvreport'
import { Route as ChangePasswordRouteImport } from './routes/changePassword'
import { Route as AutomatchRouteImport } from './routes/automatch'
import { Route as AddUserRouteImport } from './routes/addUser'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResolveClientIdRouteImport } from './routes/resolve.$clientId'
import { Route as ClientClientIdRouteImport } from './routes/client.$clientId'

const UsersListRoute = UsersListRouteImport.update({
  id: '/usersList',
  path: '/usersList',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CsvreportRoute = CsvreportRouteImport.update({
  id: '/csvreport',
  path: '/csvreport',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/changePassword',
  path: '/changePassword',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomatchRoute = AutomatchRouteImport.update({
  id: '/automatch',
  path: '/automatch',
  getParentRoute: () => rootRouteImport,
} as any)
const AddUserRoute = AddUserRouteImport.update({
  id: '/addUser',
  path: '/addUser',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResolveClientIdRoute = ResolveClientIdRouteImport.update({
  id: '/resolve/$clientId',
  path: '/resolve/$clientId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientClientIdRoute = ClientClientIdRouteImport.update({
  id: '/client/$clientId',
  path: '/client/$clientId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/addUser': typeof AddUserRoute
  '/automatch': typeof AutomatchRoute
  '/changePassword': typeof ChangePasswordRoute
  '/csvreport': typeof CsvreportRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/review': typeof ReviewRoute
  '/usersList': typeof UsersListRoute
  '/client/$clientId': typeof ClientClientIdRoute
  '/resolve/$clientId': typeof ResolveClientIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/addUser': typeof AddUserRoute
  '/automatch': typeof AutomatchRoute
  '/changePassword': typeof ChangePasswordRoute
  '/csvreport': typeof CsvreportRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/review': typeof ReviewRoute
  '/usersList': typeof UsersListRoute
  '/client/$clientId': typeof ClientClientIdRoute
  '/resolve/$clientId': typeof ResolveClientIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/addUser': typeof AddUserRoute
  '/automatch': typeof AutomatchRoute
  '/changePassword': typeof ChangePasswordRoute
  '/csvreport': typeof CsvreportRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/review': typeof ReviewRoute
  '/usersList': typeof UsersListRoute
  '/client/$clientId': typeof ClientClientIdRoute
  '/resolve/$clientId': typeof ResolveClientIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/addUser'
    | '/automatch'
    | '/changePassword'
    | '/csvreport'
    | '/login'
    | '/logout'
    | '/review'
    | '/usersList'
    | '/client/$clientId'
    | '/resolve/$clientId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/addUser'
    | '/automatch'
    | '/changePassword'
    | '/csvreport'
    | '/login'
    | '/logout'
    | '/review'
    | '/usersList'
    | '/client/$clientId'
    | '/resolve/$clientId'
  id:
    | '__root__'
    | '/'
    | '/addUser'
    | '/automatch'
    | '/changePassword'
    | '/csvreport'
    | '/login'
    | '/logout'
    | '/review'
    | '/usersList'
    | '/client/$clientId'
    | '/resolve/$clientId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddUserRoute: typeof AddUserRoute
  AutomatchRoute: typeof AutomatchRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  CsvreportRoute: typeof CsvreportRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  ReviewRoute: typeof ReviewRoute
  UsersListRoute: typeof UsersListRoute
  ClientClientIdRoute: typeof ClientClientIdRoute
  ResolveClientIdRoute: typeof ResolveClientIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usersList': {
      id: '/usersList'
      path: '/usersList'
      fullPath: '/usersList'
      preLoaderRoute: typeof UsersListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/csvreport': {
      id: '/csvreport'
      path: '/csvreport'
      fullPath: '/csvreport'
      preLoaderRoute: typeof CsvreportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changePassword': {
      id: '/changePassword'
      path: '/changePassword'
      fullPath: '/changePassword'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automatch': {
      id: '/automatch'
      path: '/automatch'
      fullPath: '/automatch'
      preLoaderRoute: typeof AutomatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/addUser': {
      id: '/addUser'
      path: '/addUser'
      fullPath: '/addUser'
      preLoaderRoute: typeof AddUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resolve/$clientId': {
      id: '/resolve/$clientId'
      path: '/resolve/$clientId'
      fullPath: '/resolve/$clientId'
      preLoaderRoute: typeof ResolveClientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/$clientId': {
      id: '/client/$clientId'
      path: '/client/$clientId'
      fullPath: '/client/$clientId'
      preLoaderRoute: typeof ClientClientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddUserRoute: AddUserRoute,
  AutomatchRoute: AutomatchRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  CsvreportRoute: CsvreportRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  ReviewRoute: ReviewRoute,
  UsersListRoute: UsersListRoute,
  ClientClientIdRoute: ClientClientIdRoute,
  ResolveClientIdRoute: ResolveClientIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
