import { useMutation, useQuery } from '@tanstack/react-query'

import { PageHeader } from '#/components/PageHeader'
import { Badge } from '#/components/ui/badge'
import { Button } from '#/components/ui/button'
import { Card, CardContent } from '#/components/ui/card'
import { backendPublicUrl, fetchCSVReport, fetchCSVUploads } from '#/lib/ocrux'

export function CsvReportPage() {
  const uploadsQuery = useQuery({
    queryKey: ['csv-uploads'],
    queryFn: fetchCSVUploads,
  })

  const downloadMutation = useMutation({
    mutationFn: fetchCSVReport,
    onSuccess: (path) => {
      window.open(backendPublicUrl(path), '_blank', 'noopener,noreferrer')
    },
  })

  return (
    <section className="grid gap-4">
      <PageHeader
        eyebrow="Reporting"
        title="CSV Reports"
        description="Download the CSV upload report workbook generated by the backend."
      />

      <div className="grid gap-3">
        {(uploadsQuery.data || []).map((upload) => (
          <Card key={upload.uuid} className="border-white/10 bg-white/5 text-white">
            <CardContent className="flex flex-wrap items-center justify-between gap-3 p-4">
              <div className="grid gap-1">
                <div className="font-semibold">{upload.name}</div>
                <div className="text-sm text-slate-300">{upload.date}</div>
              </div>
              <div className="flex items-center gap-2">
                <Badge variant="outline" className="border-white/10 bg-white/5 text-slate-200">{upload.reportId}</Badge>
                <Button
                  type="button"
                  onClick={() => downloadMutation.mutate(upload.uuid)}
                  disabled={downloadMutation.isPending}
                >
                  Download report
                </Button>
              </div>
            </CardContent>
          </Card>
        ))}
        {!uploadsQuery.data?.length ? (
          <Card className="border-white/10 bg-white/5 text-white">
            <CardContent className="p-4 text-slate-300">
              {uploadsQuery.isLoading ? 'Loading CSV reports...' : 'No CSV uploads found.'}
            </CardContent>
          </Card>
        ) : null}
      </div>
    </section>
  )
}
