import { useMutation, useQuery } from '@tanstack/react-query'

import { PageHeader } from '#/components/PageHeader'
import { Badge } from '#/components/ui/badge'
import { Button } from '#/components/ui/button'
import { Card, CardContent } from '#/components/ui/card'
import { backendPublicUrl, fetchCSVReport, fetchCSVUploads } from '#/lib/ocrux'
import { Download, FileSpreadsheet } from 'lucide-react'

export function CsvReportPage() {
  const uploadsQuery = useQuery({
    queryKey: ['csv-uploads'],
    queryFn: fetchCSVUploads,
  })

  const downloadMutation = useMutation({
    mutationFn: fetchCSVReport,
    onSuccess: (path) => {
      window.open(backendPublicUrl(path), '_blank', 'noopener,noreferrer')
    },
  })

  return (
    <div className="flex-1 space-y-4 p-8 pt-6">
      <PageHeader
        title="CSV Reports"
        description="Download the CSV upload report workbook generated by the backend."
      />

      <div className="grid gap-4">
        {(uploadsQuery.data || []).map((upload) => (
          <Card key={upload.uuid}>
            <CardContent className="flex items-center justify-between p-4">
              <div className="flex items-center space-x-4">
                <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-muted">
                  <FileSpreadsheet className="h-5 w-5 text-muted-foreground" />
                </div>
                <div className="space-y-1">
                  <p className="text-sm font-medium leading-none">{upload.name}</p>
                  <p className="text-xs text-muted-foreground">{upload.date}</p>
                </div>
              </div>
              <div className="flex items-center gap-3">
                <Badge variant="secondary" className="font-mono text-[10px]">
                  {upload.reportId}
                </Badge>
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => downloadMutation.mutate(upload.uuid)}
                  disabled={downloadMutation.isPending}
                >
                  <Download className="mr-2 h-3.5 w-3.5" />
                  Download
                </Button>
              </div>
            </CardContent>
          </Card>
        ))}
        {!uploadsQuery.data?.length && (
          <div className="flex h-[200px] items-center justify-center rounded-lg border border-dashed">
            <p className="text-sm text-muted-foreground">
              {uploadsQuery.isLoading ? 'Loading CSV reports...' : 'No CSV uploads found.'}
            </p>
          </div>
        )}
      </div>
    </div>
  )
}
